"""

"""

import json
import os
import warnings
from datetime import datetime

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.layers import (Input, Conv1D, MaxPooling1D, UpSampling1D,
                                     Dense, Flatten, Reshape, BatchNormalization,
                                     Dropout, Add)
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import mean_squared_error, mean_absolute_error

warnings.filterwarnings('ignore')


# ====================== 1. 加载DeepAE生成的虚拟样本 ======================
def load_conv_ae_data():
    """
    加载为CONV-AE准备的数据 - 使用DeepAE生成的100000个虚拟样本
    """
    print("📂 Loading CONV-AE data (using DeepAE-generated virtual samples)...")

    # 使用DeepAE生成的虚拟样本路径
    data_dir = r"D:\Oswaldo's surf project\My Database"
    virtual_samples_path = os.path.join(data_dir, "virtual_samples_100000.npy")

    # 检查文件是否存在
    if not os.path.exists(virtual_samples_path):
        print(f"❌ DeepAE virtual samples file not found: {virtual_samples_path}")
        print("Please run DeepAE_realize.py first to generate the data")
        return None, None, None

    try:
        # 加载虚拟样本
        X_conv = np.load(virtual_samples_path)

        # 检查数据形状
        print(f"✅ Successfully loaded DeepAE virtual samples:")
        print(f"  Original shape: {X_conv.shape}")
        print(f" Number of samples: {X_conv.shape[0]:,}")
        print(f"  Timesteps: {X_conv.shape[1]} hours")
        print(f"  Number of features: {X_conv.shape[2]}")
        print(f"  Data source: DeepAE virtual samples")
        print(f"  Using the exact same 100000 samples as DeepAE/LSTM/CONV-AE")

        # 加载DeepAE的特征映射
        feature_mapping_path = os.path.join(data_dir, "Merge_and_DAEfeature_mapping.json")
        if os.path.exists(feature_mapping_path):
            with open(feature_mapping_path, 'r', encoding='utf-8') as f:
                feature_mapping = json.load(f)
            print(f"✅ Successfully loaded DeepAE feature mapping")
        else:
            # 创建简单特征映射
            feature_mapping = {
                "hour_feature_names": [f"feature_{i}" for i in range(X_conv.shape[2])],
                "note": "Auto-generated feature mapping",
                "data_source": "DeepAE virtual samples"
            }
            print("⚠️  Using auto-generated feature mapping")

        # 创建CONV-AE配置
        conv_config = {
            "n_samples": X_conv.shape[0],
            "sequence_hours": X_conv.shape[1],
            "n_features": X_conv.shape[2],
            "data_source": "DeepAE_virtual_samples",
            "description": "CONV-AE uses 35,040 virtual 24-hour samples generated by DeepAE",
            "note": "Uses the exact same 35,040 samples as other models for fair comparison"
        }

        return X_conv, conv_config, feature_mapping

    except Exception as e:
        print(f"❌ Error loading file: {e}")
        return None, None, None


# ====================== 2. 构建Conv-AE模型 ======================
def build_conv_autoencoder(sequence_length=24, n_features=11,
                           filters=[32, 64, 128], kernel_size=3,
                           encoding_dim=32):
    """
    构建一维卷积自编码器 (Conv1D AutoEncoder)

    参数:
        sequence_length: 序列长度 (24小时)
        n_features: 特征数量
        filters: 每层卷积核数量
        kernel_size: 卷积核大小
        encoding_dim: 编码维度
    """
    print(f"\n🔧 Building CONV-AutoEncoder model:")
    print(f"  Input shape: ({sequence_length}, {n_features})")
    print(f"  Convolutional filters: {filters}")
    print(f"  Encoding dimension: {encoding_dim}")

    # ====== 编码器 ======
    inputs = Input(shape=(sequence_length, n_features), name='conv_input')

    x = inputs

    # 卷积编码层
    for i, f in enumerate(filters):
        x = Conv1D(filters=f, kernel_size=kernel_size, activation='relu',
                   padding='same', name=f'encoder_conv{i + 1}')(x)
        x = BatchNormalization(name=f'encoder_bn{i + 1}')(x)
        x = MaxPooling1D(pool_size=2, padding='same', name=f'encoder_pool{i + 1}')(x)
        x = Dropout(0.2, name=f'encoder_dropout{i + 1}')(x)

    # 展平并编码
    x = Flatten(name='encoder_flatten')(x)
    encoded = Dense(encoding_dim, activation='relu', name='bottleneck')(x)

    # ====== 解码器 ======
    # 重塑为卷积层需要的形状
    decoded = Dense(x.shape[1], activation='relu', name='decoder_dense')(encoded)

    # 需要计算重塑后的形状
    # 计算经过编码器后的尺寸
    conv_shape = None
    for i, f in enumerate(filters):
        if i == 0:
            conv_shape = (sequence_length // (2 ** (i + 1)), f)
        else:
            conv_shape = (conv_shape[0] // 2, f)

    decoded = Reshape(conv_shape, name='decoder_reshape')(decoded)

    # 反卷积层（逆顺序）
    for i, f in enumerate(reversed(filters)):
        decoded = Conv1D(filters=f, kernel_size=kernel_size, activation='relu',
                         padding='same', name=f'decoder_conv{i + 1}')(decoded)
        decoded = BatchNormalization(name=f'decoder_bn{i + 1}')(decoded)
        decoded = UpSampling1D(size=2, name=f'decoder_upsample{i + 1}')(decoded)

    # 最后一层卷积，输出与输入相同形状
    outputs = Conv1D(filters=n_features, kernel_size=kernel_size,
                     activation='linear', padding='same', name='output')(decoded)

    # ====== 完整模型 ======
    autoencoder = Model(inputs, outputs, name='conv_autoencoder')

    # 编码器模型（用于特征提取）
    encoder = Model(inputs, encoded, name='conv_encoder')

    # 计算参数
    total_params = autoencoder.count_params()
    trainable_params = np.sum([np.prod(v.shape) for v in autoencoder.trainable_weights])
    non_trainable_params = total_params - trainable_params

    print(f"\n📊 initial model parameters count:")
    print(f"  total parameters: {total_params:,}")
    print(f"  trainable parameters: {trainable_params:,}")
    print(f"  Non-trainable parameters: {non_trainable_params:,}")
    # print(f"  Target parameters: ~8000(Similar to the Conv-AE in the paper)")

    return autoencoder, encoder, total_params


# ====================== 3. 构建改进的Conv-AE（残差连接） ======================
def build_residual_conv_ae(sequence_length=24, n_features=11):
    """
    构建带残差连接的Conv-AE，更接近论文中的结构
    """
    print(f"\n🔧 Building improved Residual CONV-AE:")
    print(f"  Input shape: ({sequence_length}, {n_features})")

    inputs = Input(shape=(sequence_length, n_features))

    # ====== 编码器 ======
    # 第一卷积块
    x = Conv1D(32, kernel_size=5, padding='same', activation='relu')(inputs)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2, padding='same')(x)

    # 第二卷积块
    x = Conv1D(64, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = MaxPooling1D(pool_size=2, padding='same')(x)

    # 第三卷积块
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    encoded = MaxPooling1D(pool_size=2, padding='same')(x)

    # ====== 解码器 ======
    # 第一反卷积块
    x = Conv1D(128, kernel_size=3, padding='same', activation='relu')(encoded)
    x = BatchNormalization()(x)
    x = UpSampling1D(size=2)(x)

    # 第二反卷积块
    x = Conv1D(64, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = UpSampling1D(size=2)(x)

    # 第三反卷积块
    x = Conv1D(32, kernel_size=3, padding='same', activation='relu')(x)
    x = BatchNormalization()(x)
    x = UpSampling1D(size=2)(x)

    # 输出层
    outputs = Conv1D(n_features, kernel_size=5, padding='same', activation='linear')(x)

    # ====== 完整模型 ======
    autoencoder = Model(inputs, outputs, name='residual_conv_ae')
    encoder = Model(inputs, encoded, name='residual_conv_encoder')

    # 计算参数
    total_params = autoencoder.count_params()
    trainable_params= np.sum([np.prod(v.shape) for v in autoencoder.trainable_weights])
    non_trainable_params = total_params - trainable_params

    print(f"\n📊 optimized model parameters count:")
    print(f"  total parameters: {total_params:,}")
    print(f"  trainable parameters: {trainable_params:,}")
    print(f"  Non-trainable parameters: {non_trainable_params:,}")
    print(f"  Target parameters: ~8000(Similar to the Conv-AE in the paper)")

    return autoencoder, encoder, total_params


# ====================== 4. 数据准备函数 ======================
def prepare_conv_train_val_split(X_conv, train_ratio=0.85, val_ratio=0.15, shuffle=True):
    """
    为CONV-AE准备训练和验证数据
    """
    n_samples = X_conv.shape[0]

    if shuffle:
        # 随机打乱
        indices = np.random.permutation(n_samples)
        X_shuffled = X_conv[indices]
    else:
        X_shuffled = X_conv

    # 划分训练集、验证集
    train_end = int(n_samples * train_ratio)
    val_end = train_end + int(n_samples * val_ratio)

    X_train = X_shuffled[:train_end]
    X_val = X_shuffled[train_end:val_end]

    print(f"\n📊 CONV-AE dataset splitting:")
    print(f"  Training Set: {X_train.shape[0]:,} samples ({train_ratio * 100:.1f}%)")
    print(f"  Validation Set: {X_val.shape[0]:,} samples ({val_ratio * 100:.1f}%)")
    print(f"  Total Samples: {n_samples:,}")

    return X_train, X_val


# ====================== 5. 模型训练 ======================
def train_conv_autoencoder(X_train, X_val, sequence_length, n_features, epochs=80):
    """
    训练CONV Autoencoder
    """
    print(f"\n🚀 start training CONV-AE...")

    # 构建模型 - 使用改进版本，参数更接近论文
    autoencoder, encoder, total_params = build_residual_conv_ae(
        sequence_length=sequence_length,
        n_features=n_features
    )

    # 编译模型
    autoencoder.compile(
        optimizer=Adam(learning_rate=0.001),
        loss='mse',
        metrics=['mae']
    )

    print("\n📋 Model Architecture Summary:")
    autoencoder.summary()

    # 回调函数
    callbacks = [
        # EarlyStopping(
        #     monitor='val_loss',
        #     patience=15,
        #     restore_best_weights=True,
        #     verbose=1
        # ),
        ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=10,
            min_lr=1e-6,
            verbose=1
        )
    ]

    # 训练模型
    print(f"\n📈 Training Details:")
    print(f"  Batch Size: 128")
    print(f"  Max Epochs: {epochs}")

    history = autoencoder.fit(
        X_train, X_train,
        validation_data=(X_val, X_val),
        epochs=epochs,
        batch_size=128,
        # callbacks=callbacks,
        verbose=1
    )

    return autoencoder, encoder, history, total_params


# ====================== 6. 评估和异常检测 ======================
# ====================== 6. 评估和异常检测 ======================
def evaluate_conv_anomalies(autoencoder, X_val, X_test=None, percentile=95):
    """
    评估CONV-AE模型并检测异常
    """
    print("\n📈 CONV-AE Model Evaluation Results:")

    # 在验证集上评估
    val_loss, val_mae = autoencoder.evaluate(X_val, X_val, verbose=0)
    print(f"  Validation loss (MSE): {val_loss:.6f}")
    print(f"  Validation MAE: {val_mae:.6f}")

    # 计算验证集重建误差
    val_reconstructed = autoencoder.predict(X_val, verbose=0)
    val_errors = np.mean((X_val - val_reconstructed) ** 2, axis=(1, 2))

    # 计算阈值 (95th percentile)
    threshold = np.percentile(val_errors, percentile)
    print(f"  Validation set reconstruction error {percentile}th percentile threshold: {threshold:.6f}")

    # 在验证集上检测异常（关键：加上这行输出）
    val_anomalies = val_errors > threshold
    val_anomalies_count = np.sum(val_anomalies)
    val_anomaly_ratio = val_anomalies_count / len(X_val) * 100

    print(f"  Detected {val_anomalies_count} anomalous samples out of {len(X_val)} total samples")
    print(f"  Anomaly ratio: {val_anomaly_ratio:.2f}%")

    # 如果传入了测试集
    if X_test is not None:
        test_reconstructed = autoencoder.predict(X_test, verbose=0)
        test_errors = np.mean((X_test - test_reconstructed) ** 2, axis=(1, 2))

        anomalies = test_errors > threshold
        anomalies_count = np.sum(anomalies)
        anomaly_ratio = anomalies_count / len(X_test) * 100

        return threshold, val_anomalies_count, val_anomaly_ratio, test_errors, test_reconstructed, val_errors
    else:
        # 注意：这里要返回验证集的异常计数和比例
        return threshold, val_anomalies_count, val_anomaly_ratio, val_errors, val_reconstructed, val_errors

# ====================== 7. 可视化函数 ======================
def visualize_conv_results(history, X_original, X_reconstructed, errors, threshold,
                           feature_mapping, autoencoder,total_params, model_name="CONV AutoEncoder"):
    """
    可视化CONV-AE训练结果和异常检测
    """
    print(f"\n📊 Generating CONV_AE visualization results...")

    # 设置正确的保存路径
    base_dir = r"D:\Oswaldo's surf project\My Database"
    os.makedirs(base_dir, exist_ok=True)

    # 设置绘图风格
    plt.style.use('seaborn-v0_8-darkgrid')
    fig = plt.figure(figsize=(20, 12))

    # 1. 训练损失变化
    ax1 = plt.subplot(3, 3, 1)
    epochs = range(1, len(history.history['loss']) + 1)
    ax1.plot(epochs, history.history['loss'], label='Training Loss', linewidth=2)
    ax1.plot(epochs, history.history['val_loss'], label='Validation Loss', linewidth=2)
    ax1.set_title(f'{model_name} - Training History', fontsize=14, fontweight='bold')
    ax1.set_xlabel('Epoch', fontsize=12)
    ax1.set_ylabel('MSE Loss', fontsize=12)
    ax1.legend()
    ax1.grid(True, alpha=0.3)

    # 2. MAE变化
    ax2 = plt.subplot(3, 3, 2)
    ax2.plot(epochs, history.history['mae'], label='Training MAE', linewidth=2, color='orange')
    if 'val_mae' in history.history:
        ax2.plot(epochs, history.history['val_mae'], label='Validation MAE', linewidth=2, color='red')
    ax2.set_title('MAE History', fontsize=14, fontweight='bold')
    ax2.set_xlabel('Epoch', fontsize=12)
    ax2.set_ylabel('Mean Absolute Error', fontsize=12)
    ax2.legend()
    ax2.grid(True, alpha=0.3)

    # 3. 重建误差分布
    ax3 = plt.subplot(3, 3, 3)
    n_bins = min(100, len(errors) // 10)
    ax3.hist(errors, bins=n_bins, alpha=0.7, color='skyblue', edgecolor='black', density=True)
    ax3.axvline(x=threshold, color='red', linestyle='--', linewidth=2,
                label=f'Threshold ({threshold:.4f})')

    # 添加高斯分布拟合
    from scipy.stats import norm
    mu, std = norm.fit(errors)
    xmin, xmax = ax3.get_xlim()
    x = np.linspace(xmin, xmax, 100)
    p = norm.pdf(x, mu, std)
    ax3.plot(x, p, 'k', linewidth=2, label=f'Normal fit: μ={mu:.4f}, σ={std:.4f}')

    ax3.set_title('Reconstruction Error Distribution', fontsize=14, fontweight='bold')
    ax3.set_xlabel('Reconstruction Error (MSE)', fontsize=12)
    ax3.set_ylabel('Density', fontsize=12)
    ax3.legend()
    ax3.grid(True, alpha=0.3)

    # 4. 原始vs重建特征对比（第一个样本的第一个特征）
    ax4 = plt.subplot(3, 3, 4)
    if len(X_original) > 0:
        sample_idx = 0
        feature_idx = 0

        # 获取第一个样本的所有时间步
        time_steps = range(X_original[sample_idx].shape[0])
        original_values = X_original[sample_idx][:, feature_idx]
        reconstructed_values = X_reconstructed[sample_idx][:, feature_idx]

        ax4.plot(time_steps, original_values, label='Original', linewidth=2, alpha=0.8)
        ax4.plot(time_steps, reconstructed_values, label='Reconstructed', linewidth=2,
                 alpha=0.8, color='red', linestyle='--')

        ax4.set_title(f'Sample {sample_idx} - Feature {feature_idx} Comparison',
                      fontsize=14, fontweight='bold')
        ax4.set_xlabel('Time Step', fontsize=12)
        ax4.set_ylabel('Feature Value', fontsize=12)
        ax4.legend()
        ax4.grid(True, alpha=0.3)

    # 5. 重建误差时间序列
    ax5 = plt.subplot(3, 3, 5)
    sample_indices = range(len(errors))

    # 对误差进行平滑
    window_size = min(100, len(errors) // 10)
    if window_size > 1:
        errors_smooth = np.convolve(errors, np.ones(window_size) / window_size, mode='valid')
        indices_smooth = sample_indices[:len(errors_smooth)]
        ax5.plot(indices_smooth, errors_smooth, linewidth=1, alpha=0.7, color='blue',
                 label='Smoothed Error')

    ax5.plot(sample_indices, errors, linewidth=0.5, alpha=0.3, color='gray', label='Raw Error')
    ax5.axhline(y=threshold, color='red', linestyle='--', linewidth=2,
                label=f'Threshold ({threshold:.4f})')

    # 标记异常
    anomalies = errors > threshold
    anomaly_indices = np.where(anomalies)[0]
    ax5.scatter(anomaly_indices, errors[anomaly_indices],
                color='red', s=10, alpha=0.5, label='Anomalies')

    ax5.set_title('Reconstruction Error Time Series', fontsize=14, fontweight='bold')
    ax5.set_xlabel('Sample Index', fontsize=12)
    ax5.set_ylabel('Reconstruction Error', fontsize=12)
    ax5.legend(loc='upper right', fontsize=10)
    ax5.grid(True, alpha=0.3)

    # 6. 卷积特征图可视化（第一个样本）
    ax6 = plt.subplot(3, 3, 6)
    if len(X_original) > 0:
        sample_idx = 0

        # 获取中间卷积层的激活
        layer_outputs = [layer.output for layer in autoencoder.layers if 'conv' in layer.name]

        # 检查是否找到了卷积层
        if layer_outputs:
            activation_model = Model(inputs=autoencoder.input, outputs=layer_outputs)
            activations = activation_model.predict(X_original[sample_idx:sample_idx + 1], verbose=0)

            # 显示第一个卷积层的特征图
            if len(activations) > 0:
                first_layer_activation = activations[0][0]  # 第一个样本，第一个卷积层
                n_filters = min(16, first_layer_activation.shape[1])  # 最多显示16个滤波器

                for i in range(n_filters):
                    ax6.plot(first_layer_activation[:, i], alpha=0.5, linewidth=1)

                ax6.set_title(f'Sample {sample_idx} - Conv Layer Activations',
                              fontsize=14, fontweight='bold')
                ax6.set_xlabel('Time Step', fontsize=12)
                ax6.set_ylabel('Activation Value', fontsize=12)
                ax6.grid(True, alpha=0.3)
        else:
            ax6.text(0.5, 0.5, 'No Conv Layers Found\nin Model',
                     ha='center', va='center', transform=ax6.transAxes, fontsize=12)
            ax6.set_title('Conv Layer Activations', fontsize=14, fontweight='bold')

    # 7. 学习率变化
    ax7 = plt.subplot(3, 3, 7)
    if 'lr' in history.history:
        ax7.plot(epochs, history.history['lr'], linewidth=2, color='green')
        ax7.set_title('Learning Rate Schedule', fontsize=14, fontweight='bold')
        ax7.set_xlabel('Epoch', fontsize=12)
        ax7.set_ylabel('Learning Rate', fontsize=12)
        ax7.grid(True, alpha=0.3)
    else:
        ax7.text(0.5, 0.5, 'Learning Rate\nData Not Available',
                 ha='center', va='center', transform=ax7.transAxes, fontsize=12)
        ax7.set_title('Learning Rate Schedule', fontsize=14, fontweight='bold')

    # 8. 模型参数对比
    ax8 = plt.subplot(3, 3, 8)
    models = ['DeepAE', 'LSTM-AE', 'CONV-AE']
    params = [29769, total_params, total_params]  # 需要从历史结果获取
    colors = ['lightblue', 'lightgreen', 'lightcoral']

    bars = ax8.bar(models, params, color=colors, alpha=0.8)
    ax8.set_title('Model Parameter Comparison', fontsize=14, fontweight='bold')
    ax8.set_ylabel('Number of Parameters', fontsize=12)
    ax8.grid(True, alpha=0.3, axis='y')

    # 添加数值标签
    for bar, param in zip(bars, params):
        ax8.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1000,
                 f'{param:,}', ha='center', va='bottom', fontsize=10)

    # 9. 性能对比
    ax9 = plt.subplot(3, 3, 9)
    if np.sum(errors > threshold) > 0:
        # 计算不同阈值下的性能
        thresholds = np.percentile(errors, range(90, 100))
        anomaly_rates = []

        for t in thresholds:
            anomaly_rate = np.sum(errors > t) / len(errors) * 100
            anomaly_rates.append(anomaly_rate)

        ax9.plot(thresholds, anomaly_rates, 'o-', linewidth=2, markersize=6)
        ax9.axvline(x=threshold, color='red', linestyle='--', linewidth=1.5,
                    label=f'95th percentile ({threshold:.4f})')
        ax9.set_title('Anomaly Rate vs Threshold', fontsize=14, fontweight='bold')
        ax9.set_xlabel('Threshold', fontsize=12)
        ax9.set_ylabel('Anomaly Rate (%)', fontsize=12)
        ax9.legend()
        ax9.grid(True, alpha=0.3)
    else:
        ax9.text(0.5, 0.5, 'No Anomalies Detected\nwith Current Threshold',
                 ha='center', va='center', transform=ax9.transAxes, fontsize=12)
        ax9.set_title('Anomaly Detection Performance', fontsize=14, fontweight='bold')

    plt.tight_layout()

    # 保存图表
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_path = os.path.join(base_dir, f"conv_visualization_{timestamp}.png")

    try:
        plt.savefig(save_path, dpi=150, bbox_inches='tight')
        print(f"📸 CONV visualization results saved to: {save_path}")
    except Exception as e:
        print(f"⚠️  Failed to save image: {e}")
        alt_path = f"conv_visualization_{timestamp}.png"
        plt.savefig(alt_path, dpi=150, bbox_inches='tight')
        print(f"📸 Saved to current directory: {alt_path}")

    plt.close()

    # 输出特征级分析
    if len(X_original) > 0:
        print("\n📊 CONV_AE Reconstruction Error Analysis (First Sample):")
        feature_errors = np.mean((X_original[0] - X_reconstructed[0]) ** 2, axis=0)

        if 'hour_feature_names' in feature_mapping:
            hour_feature_names = feature_mapping['hour_feature_names']
            if len(hour_feature_names) == len(feature_errors):
                print("  Feature Reconstruction Error Ranking:")
                sorted_indices = np.argsort(feature_errors)[::-1]
                for i, idx in enumerate(sorted_indices[:5]):
                    print(f"    {i + 1}. {hour_feature_names[idx]}: {feature_errors[idx]:.6f}")


# ====================== 8. 保存模型 ======================
def save_conv_models(autoencoder, encoder, save_path):
    """
    Save trained CONV models
    """
    # Ensure the save path exists
    os.makedirs(save_path, exist_ok=True)

    # Save in HDF5 format
    try:
        autoencoder.save(os.path.join(save_path, "conv_autoencoder_model2.h5"))
        encoder.save(os.path.join(save_path, "conv_encoder_model2.h5"))

        print(f"\n💾 CONV models saved to: {save_path}")
        print(f"  - conv_autoencoder_model2.h5")
        print(f"  - conv_encoder_model2.h5")
    except Exception as e:
        print(f"⚠️  Failed to save models: {e}")
        print("Attempting to save to current directory...")
        autoencoder.save("conv_autoencoder_model2.h5")
        encoder.save("conv_encoder_model2.h5")


# ====================== 9. 对比分析 ======================
# def create_comprehensive_comparison(conv_results, deepae_results=None, lstm_results=None):
#     """
#     创建全面的模型对比分析
#     """
#     print("\n" + "=" * 80)
#     print("📊 全面模型对比分析")
#     print("=" * 80)
#
#     # 数据准备
#     comparison_data = {
#         'Model': ['DeepAE', 'LSTM-AE', 'CONV-AE'],
#         'Params': ['29,769', '~1,200,000', f'{conv_results["total_params"]:,}'],
#         'Val_MAE': ['0.1785', '0.2065', f'{conv_results["val_mae"]:.4f}'],
#         'Anomaly_Rate': ['4.56%', '4.61%', f'{conv_results["all_anomaly_ratio"]:.2f}%'],
#         'Input_Shape': ['24×11+全局', '24×11', '24×11'],
#         'Architecture': ['Dense Layers', 'LSTM Layers', 'Conv1D Layers'],
#         'Training_Time': ['~10min', '~30min', '~20min']
#     }
#
#     # 打印对比表格
#     print(f"\n{'模型':<12} {'参数':<12} {'验证MAE':<12} {'异常率':<12} {'架构':<15}")
#     print("-" * 63)
#
#     for i in range(len(comparison_data['Model'])):
#         print(f"{comparison_data['Model'][i]:<12} "
#               f"{comparison_data['Params'][i]:<12} "
#               f"{comparison_data['Val_MAE'][i]:<12} "
#               f"{comparison_data['Anomaly_Rate'][i]:<12} "
#               f"{comparison_data['Architecture'][i]:<15}")
#
#     print("-" * 63)
#
#     # 保存为CSV
#     df = pd.DataFrame(comparison_data)
#     save_path = r"D:\Oswaldo's surf project\My Database\model_comparison_summary.csv"
#     df.to_csv(save_path, index=False, encoding='utf-8-sig')
#     print(f"\n💾 对比结果已保存为CSV: {save_path}")
#
#     return df


# ====================== 10. 主流程 ======================
def main():
    print("=" * 80)
    print("CONVOLUTIONAL AUTOENCODER  TRAINING PIPELINE")
    print("=" * 80)

    # 配置路径
    base_path = r"D:\Oswaldo's surf project\My Database"
    model_save_path = os.path.join(base_path, "models\\")

    # 确保目录存在
    os.makedirs(base_path, exist_ok=True)
    os.makedirs(model_save_path, exist_ok=True)

    # 1. 加载CONV-AE数据（使用DeepAE虚拟样本）
    X_conv, conv_config, feature_mapping = load_conv_ae_data()
    if X_conv is None:
        print("❌ Failed to load CONV-AE data, exiting process")
        return

    # 2. 准备训练数据
    X_train, X_val = prepare_conv_train_val_split(
        X_conv,
        train_ratio=0.85,
        val_ratio=0.15,
        shuffle=True
    )

    # 3. 训练CONV Autoencoder
    sequence_length = X_conv.shape[1]
    n_features = X_conv.shape[2]

    autoencoder, encoder, history, total_params = train_conv_autoencoder(
        X_train, X_val,
        sequence_length=sequence_length,
        n_features=n_features,
        epochs=80
    )

    # 4. 在验证集上评估
    # 4. 在验证集上评估
    print("\n🔍 Evaluating CONV model on validation set:")
    threshold, val_anomalies_count, val_anomaly_ratio, val_errors, val_reconstructed, _ = evaluate_conv_anomalies(
        autoencoder, X_val, X_val, percentile=95
    )

    # 5. 在整个数据集上评估
    print("\n🔍 Evaluating on the complete CONV dataset:")
    X_all = X_conv

    all_reconstructed = autoencoder.predict(X_all, verbose=0)
    all_errors = np.mean((X_all - all_reconstructed) ** 2, axis=(1, 2))

    # 检测异常
    all_anomalies = all_errors > threshold
    all_anomalies_count = np.sum(all_anomalies)
    all_anomaly_ratio = all_anomalies_count / len(X_all) * 100

    print(f"  Total samples: {len(X_all):,}")
    print(f"  Anomalies detected: {all_anomalies_count:,}")
    print(f"  Anomaly proportion: {all_anomaly_ratio:.2f}%")

    # 6. 可视化结果
    print("\n📊 Generating visualization for all CONV samples:")
    visualize_conv_results(
        history, X_all, all_reconstructed, all_errors, threshold,
        feature_mapping, autoencoder,total_params,model_name="CONV AutoEncoder (100000 samples)"
    )

    # 7. 保存模型
    save_conv_models(autoencoder, encoder, model_save_path)

    # 🔍 新增：输出模型性能总结（与LSTM一致）
    print("\n" + "=" * 80)
    print("📋 CONV-AE Training Completion Report")
    print("=" * 80)

    print(f"\n📊 CONV Model Performance Summary:")
    print(f"  Total samples: {X_conv.shape[0]:,}")
    print(f"  Actual training samples used: {X_train.shape[0]:,}")
    print(f"  Actual validation samples used: {X_val.shape[0]:,}")
    print(f"  Total params: {total_params:,}")
    print(f"  Validation loss (MSE): {history.history['val_loss'][-1]:.6f}")
    print(f"  95th percentile threshold (validation): {threshold:.6f}")
    print(f"  Anomaly detection (all samples): {all_anomalies_count:,} / {len(X_all):,} ({all_anomaly_ratio:.2f}%)")

    # 8. 生成分析报告
    conv_results = {
        'total_params': total_params,
        'val_mae': history.history.get('val_mae', [0])[-1],
        'val_loss': history.history['val_loss'][-1],
        'all_anomaly_ratio': all_anomaly_ratio,
        'all_anomalies_count': all_anomalies_count,
        'threshold': threshold
    }

    # 创建对比分析
    # create_comprehensive_comparison(conv_results)

    # 9. 保存详细结果
    results = {
        'model_name': 'CONV_AutoEncoder',
        'total_params': int(total_params),
        'n_samples': X_conv.shape[0],
        'n_train_samples': X_train.shape[0],
        'n_val_samples': X_val.shape[0],
        'sequence_length': int(sequence_length),
        'n_features': int(n_features),
        'validation_threshold': float(threshold),
        'validation_anomalies': int(val_anomalies_count),
        'all_anomalies': int(all_anomalies_count),
        'anomaly_ratio_all': float(all_anomaly_ratio),
        'anomaly_ratio_val': float(val_anomaly_ratio),
        'final_train_loss': float(history.history['loss'][-1]),
        'final_val_loss': float(history.history['val_loss'][-1]),
        'final_train_mae': float(history.history['mae'][-1]),
        'final_val_mae': float(history.history.get('val_mae', [0])[-1]),
        'training_date': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'architecture': 'Conv1D AutoEncoder with residual connections',
        'data_source':  'DeepAE virtual samples'
    }

    results_path = os.path.join(base_path, 'conv_ae_training_results2.json')
    with open(results_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, indent=2, ensure_ascii=False)

    print(f"\n💾 CONV training results saved to: {results_path}")
    print("\n🎉 CONV AutoEncoder training pipeline completed!")


# ====================== 11. 运行主流程 ======================
if __name__ == "__main__":
    # 设置TensorFlow日志级别
    tf.get_logger().setLevel('ERROR')

    # 设置matplotlib中文字体
    # plt.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']
    plt.rcParams['axes.unicode_minus'] = False

    # 运行主流程
    main()